task:
  # Xcode 12 task
  osx_instance:
    image: big-sur-xcode-12.4
  upgrade_script:
    - brew install node
    - cd ./nodejs_server_test_auth_basic_and_ssl
    - npm install
    - cd ..
    - sudo gem install cocoapods
    #- flutter channel stable
    #- flutter upgrade
    #- flutter channel dev
    #- flutter upgrade
#    - flutter channel master
#    - flutter upgrade
#    - git fetch origin master
  matrix:
#    - name: test_plugin_ios
#      env:
#        matrix:
#          CHANNEL: "master"
#          #CHANNEL: "dev"
#          #CHANNEL: "stable"
#      script:
#        - xcrun simctl list
#        - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-12 com.apple.CoreSimulator.SimRuntime.iOS-14-4 | xargs xcrun simctl boot
#        - flutter channel $CHANNEL
#        - ./test.sh $(ipconfig getifaddr en0)
    - name: test_plugin_android
      env:
        matrix:
          CHANNEL: "master"
          #CHANNEL: "dev"
          #CHANNEL: "stable"
      script:
        - mkdir -p .android && touch ~/.android/repositories.cfg
        - (yes || true) | sdkmanager "platform-tools" "platforms;android-30"
        - (yes || true) | sdkmanager --licenses
        - echo no | avdmanager create avd --force -n Flutter-Android -k "system-images;android-30;default;armeabi-v7a"
        - $ANDROID_HOME/emulator/emulator -avd Flutter-Android -no-audio -no-window
        - adb wait-for-device
        - adb shell input keyevent 82
        - flutter channel $CHANNEL
        - ./test.sh $(ipconfig getifaddr en0)
