language: dart

install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew install node
  - brew install libimobiledevice ideviceinstaller ios-deploy
  - brew install cocoapods || echo 'ignore exit(1)'
  - brew link --overwrite cocoapods
  - export FLUTTER_HOME=$HOME/flutter
  - export PATH=$HOME/flutter:$HOME/flutter/bin/:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
  - git clone https://github.com/flutter/flutter.git $FLUTTER_HOME
  - cd $FLUTTER_HOME
  - git checkout beta
  - git checkout stable
  - flutter doctor
  - flutter channel master
  - flutter upgrade
  - flutter doctor
  - cd $HOME

jobs:
  include:
    - stage: iOS Integration Tests
      os: osx
      osx_image: xcode12.3
      before_script:
        - pwd
        - cd ./flutter_inappwebview
        - cd ./nodejs_server_test_auth_basic_and_ssl
        - npm install
        - cd ..
        - xcrun simctl list
        - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-12 com.apple.CoreSimulator.SimRuntime.iOS-14-3 | xargs xcrun simctl boot
      script:
        - ./scripts/test.sh $(ipconfig getifaddr en0)