language: dart

env:
  global:
    - DARTSDK=./flutter/bin/cache/dart-sdk/bin
    - DARTFMT=$DARTSDK/dartfmt
    - FLUTTER=./flutter/bin/flutter
    - FLUTTER_UP=../flutter/bin/flutter
    - FLUTTER_GITHUB=https://github.com/flutter/flutter.git
    - PACKAGES=packages
    - ANDROID_API=30

install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew install node
  - brew install libimobiledevice ideviceinstaller ios-deploy
  - brew install cocoapods || echo 'ignore exit(1)'
  - brew link --overwrite cocoapods
  - git clone $FLUTTER_GITHUB -b stable --depth 1
  - $FLUTTER upgrade
  - $FLUTTER channel master
  - $FLUTTER upgrade
  - $FLUTTER doctor
  - $FLUTTER pub get

jobs:
  include:
    - stage: iOS Integration Tests
      os: osx
      osx_image: xcode12.3
      before_script:
        - cd ./nodejs_server_test_auth_basic_and_ssl
        - npm install
        - cd ..
        - xcrun simctl list
        - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-12 com.apple.CoreSimulator.SimRuntime.iOS-14-3 | xargs xcrun simctl boot
      script:
        - ./scripts/test.sh $(ipconfig getifaddr en0)