name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:
  flutter_inappwebview_internal_annotations:
    path: ../flutter_inappwebview_internal_annotations/

dev_dependencies:
  build_runner:
  build_test:
  test: ^1.21.1