name: test_gen
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_internal_annotations:
    path: ../flutter_inappwebview_internal_annotations/

dev_dependencies:
  build_runner: ^2.2.1
  generators:
    path: ../generators/
  lints: ^1.0.1